### PR TITLE
Add createUser(), removeUser() and authWithPassword()

### PR DESCRIPTION
**Pull request by wilsynet**
I added createUser(), removeUser() and authWithPassword().

As a consequence of that, I also needed to change AuthResponse.auth to type JsObject rather than String, although perhaps it should just be untyped.

Thoughts?

Also, if I execute async methods within a Dart test, there seems to be no way to wait for completion other than chaining async calls together using .then().  Which is what I do in the auth-credentials test group.  The test seems a bit monolithic, but if I write separate tests for createUser(), removeUser() and authWithPassword(), then there's a race toward failure.

How do you want to see these tests structured?  I would be happy to fix.

### CODE REVIEW

**Comment by alexpaluzzi** [comment]
ping @wilsynet

**Comment by sethladd** [comment]
@alexpaluzzi if you can clean up this PR so it can merge, please open a new PR and we'll merge it. Thanks!

**Comment by wilsynet** [comment]
Sorry for the delay, I missed the original email.  I'll update the PR sometime tomorrow.

**Comment by alexpaluzzi** [comment]
@wilsynet I just assumed you were enjoying the holidays! Was a friendly reminder ping. -- please let me know if there's anything I can help with.

**Comment by wilsynet** [comment]
PR updated with latest from upstream.  Conflicts resolved.

**Comment by sethladd** [comment]
Thanks!

**Comment by sethladd** [comment]
And we're live! https://pub.dartlang.org/packages/firebase

**Pull request merged**
