### PR TITLE
V4

### PR DESCRIPTION
**Pull request by kevmoo**
Closes https://github.com/firebase/firebase-dart/issues/108

### CODE REVIEW

**Comment by kevmoo** [comment]
CC @Janamou – thoughts?

**Comment by Janamou** [comment]
@kevmoo looks good! I am now looking at the rest here :-)

**Comment by Janamou** [comment]
@kevmoo Oh no, I am working on the rest of the things in the API right now (to let you know that we will not go into more collisions)

**Comment by kevmoo** [comment]
I'll finish as of now – let me land this – and you can build off it?

**Comment by Janamou** [comment]
@kevmoo ok

**Pull request merged**
