### PR TITLE
define goOffline and goOnline

### LINKED ISSUE #81: goOnline and goOffline not defined

### PR DESCRIPTION
**Pull request by sirctseb**
fix #81

### CODE REVIEW

**Comment by sirctseb** [comment]
I signed it

**Comment by sirctseb** [comment]
you're welcome

**Comment by sirctseb** [comment]
tests are failing to compile(?) but I don't know why

```
$ ./tool/travis.sh
Analyzing [lib/firebase.dart, lib/firebase_io.dart, test/firebase_test.dart]...
No issues found
00:40 +15 -1: [Firefox] compiling test/jwt_test.dart
  The null object does not have a getter 'keys'.
  
  NoSuchMethodError: method not found: 'keys'
  Receiver: null
  Arguments: []
  dart:core                                                      Object.noSuchMethod
  package:source_map_stack_trace/source_map_stack_trace.dart 80  mapStackTrace.<fn>
  package:stack_trace                                            Trace.Trace
  package:source_map_stack_trace/source_map_stack_trace.dart 55  mapStackTrace
  dart:async                                                     _StreamController.add
  package:web_socket_channel/src/copy/web_socket_impl.dart 739   WebSocketImpl.WebSocketImpl.fromSocket.<fn>
  dart:async                                                     _EventSinkWrapper.add
  package:web_socket_channel/src/copy/web_socket_impl.dart 345   _WebSocketProtocolTransformer._messageFrameEnd
  package:web_socket_channel/src/copy/web_socket_impl.dart 241   _WebSocketProtocolTransformer.add
  ===== asynchronous gap ===========================
  dart:async                                                     Future.Future.sync
  package:pool/pool.dart 120                                     Pool.withResource.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                     _Future.then
  package:pool/pool.dart 119                                     Pool.withResource

00:40 +15 -2: [Firefox] compiling test/encode_test.dart
   <same stack trace>
01:12 +15 -3: [Firefox] compiling test/firebase_test.dart
   <same stack trace>

No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

**Comment by kevmoo** [comment]
Please look at the latest code. Reopen once it's rebased.

**Pull request closed without merging**
