### PR TITLE
support timestamp/DateTime

### PR DESCRIPTION
**Pull request by kevmoo**
Fixes https://github.com/firebase/firebase-dart/issues/138

### CODE REVIEW

**Comment by kevmoo** [comment]
CC @Janamou @alextekartik

**Comment by kevmoo** [comment]
@alexpaluzzi – your code was a big help here. Thanks!

**Comment by kevmoo** [comment]
...note the handeling (or not) of UTC. JS Date is weird.

**Comment by alextekartik** [comment]
Great! indeed, too bad there is not an easy way to test the javascript type of a javascript object and to rely on some properties. If someone has an object with a member named "toDateString", we're screwed ;) !

**Comment by kevmoo** [comment]
>  If someone has an object with a member named "toDateString", we're screwed ;) !

The only JS objects we're handling are coming from the Firebase API. I think we're okay 😄

**Pull request merged**
