### PR TITLE
Add authWithOAuthPopup() and authWithOAuthRedirect() methods.

### PR DESCRIPTION
**Pull request by madisona**
added methods to authenticate with oauth providers as described here: https://www.firebase.com/docs/web/guide/user-auth.html

### CODE REVIEW

**Comment by madisona** [comment]
Short answer is... I think so.  Firebase has made it wildly easy to integrate oauth...  The only difference for any provider is the provider name: 'twitter', 'github', 'google', 'facebook'.  I've tested my app with github and google and it seems to do what I'd expect.

**Comment by sethladd** [comment]
cc @alexpaluzzi can you please take a look?

**Comment by alexpaluzzi** [comment]
@madisona This looks good. Can we update changelog?

I'm going to test with the rest of the providers.

**Comment by alexpaluzzi** [comment]
Google, Github, and Twitter all work great.

Should we add tests for this? Would need to use a personal Firebase or get client tokens/secrets added to the shared one for the providers.

**Comment by madisona** [comment]
I opened pull request #30 to update the changelog.  This current one I accidentally opened against master branch and have a couple commits that I didn't mean to go up yet.

**Pull request closed without merging**
