### PR TITLE
adds Mojo support

### LINKED ISSUE #71: Add Flutter support
[Flutter](http://flutter.io) is a new project to help developers build high-performance, high-fidelity, mobile apps for iOS and Android from a single codebase. Flutter developers need the firebase-dart package to add Firebase support to their app.

Here is an example of a Firebase app using Flutter: https://github.com/flutter/firechat-flutter

Mojo is the IPC system that Flutter apps use to call native iOS and Android SDKs. By refactoring firebase-dart into a JavaScript and Mojo backend with a common interface, we can allow the firebase-dart package to work for Flutter developers. We will need https://github.com/dart-lang/sdk/issues/24581 to be fixed before we can do this.

### PR DESCRIPTION
**Pull request by collinjackson**
fixes #71

### CODE REVIEW

**Comment by davenotik** [comment]
@sethladd so what exactly did you want us to test here? Shall a corresponding issue be opened?

**Comment by sethladd** [comment]
Hi @davenotik just let us know if we break the js-interop version of this library :)

**Comment by collinjackson** [comment]
This PR shouldn't be merged until https://github.com/dart-lang/sdk/issues/24581 is fixed. I filed #71 to track the issue. For now, Flutter developers should use the https://github.com/flutter/firebase-dart fork.

**Comment by collinjackson** [comment]
I identified an issue with this PR -- the Dart VM doesn't notify us when Firebase objects are garbage collected, so we can't close the Mojo handles and just leak them. We need to multiplex all the Firebase API calls through a single proxy, and add an API to Firebase that allows the developer to manually close the proxy if they want to release all resources associated with the Firebase. (This won't do anything in the JS implementation.)

**Comment by collinjackson** [comment]
Closing as mojo is no longer used in Flutter.

**Pull request closed without merging**
