### PR TITLE
Firebase io

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by sethladd** [comment]
lgtm

**Comment by davenotik** [comment]
firebase_io adds support for interacting via Firebase's REST API, yes? Streamlines server side Firebase usage. I've been using my own lib that abstracts that; it seemed logical that something like it should be w/ the firebase.dart lib. Cool!

**Comment by kevmoo** [comment]
@davenotik what I've added is very simple, but it gets things started.

Pull requests here are welcome!

**Comment by davenotik** [comment]
Mine's simple too, probably uglier. FWIW: https://gist.github.com/davenotik/f3af156827f7b859c9d4

**Pull request merged**
