### PR TITLE
Firestore

### PR DESCRIPTION
**Pull request by Janamou**
@kevmoo 🎉🎉🎉 You can play with Firestore 🔥 

1. You need to add a projectId/PROJECT_ID to your project
2. I don't know why but I am having a problem while running Firestore tests on Travis. It says "client is offline" and then it fails because of timeout. Running locally works :-/ Any ideas?

Thx

### CODE REVIEW

**Comment by 4cm4k1** [comment]
Boom! Thanks, @Janamou, for your hard work! I’ll maybe give this a shot before the PR is merged just to get a feel for everything.

**Comment by kortnevdmitriy** [comment]
@Janamou I am so happy with this PR. I am doing the tests now.

**Comment by kevmoo** [comment]
@4cm4k1 @kortnevdmitriy – I have limited time to dig in deeply here. If you can validate it all looks good to you, that'd be very helpful!

**Comment by Blimster** [comment]
Hi @Janamou ! First, thanks for your great work! However, I found some issues. What is the best way to report them?

Issues found:
- Example code in README.md doesn't work because of a name conflict (the firebase import has no prefix anymore).
- The firebase package doesn't work with DDC.

**Comment by kortnevdmitriy** [comment]
@Blimster  I have also faced the same issue with the firebase-firestore import.

**Comment by Janamou** [comment]
Sorry, fixed readme. Thanks!

@Blimster Can you please provide me more info to second and third bug? Thx

**Comment by Blimster** [comment]
@Janamou: Here some info for the bugs I reported:

- Dart SDK 1.24.2
- Create a document in Firestore that has a reference to another document
- Access the document like this: `firestore.doc('/foo/2345').get().then((documentSnapshot) {
    documentSnapshot.data();
  });`
- Use `pub serve --web-compiler=dartdevc`
- Open the application in Chrome. You will get an exception with this message: `CastError: Casting value of type 'JSObject<t>' to incompatible type 'JSObject<n>'`
- Open the application in Dartium and you will get an exception with this message: `TypeError: Converting circular structure to JSON`

Hope this info helps.

**Comment by kevmoo** [comment]
Do we feel like this is *most* of the way there?

Can we land it an iterate?

**Comment by kevmoo** [comment]
I'm going to squash-merge this...then we can file issues to do the cleanup!

**Comment by dunmashiku** [comment]
@Janamou and everyone, 
Thank you for all the work you do for angular dart and firebase. @Janamou I was going to add add Firestore to your angulardart sample app: https://github.com/Janamou/firebase-demo-ng. Just wanted to ask how to resolve the issue with this package not being recognized: `import 'package:firebase/firebase_firestore.dart' as fs;`
I have added the two scripts: 
`<script src="https://www.gstatic.com/firebasejs/4.8.0/firebase.js"></script>
    <script src="https://www.gstatic.com/firebasejs/4.8.0/firebase-firestore.js"></script>`

Any help greatly appreciated,
Dun

**Comment by kevmoo** [comment]
@Janamou – looks like we're going to get green here, too!

https://travis-ci.org/firebase/firebase-dart/builds/322670485

...fixed the config

**Comment by kevmoo** [comment]
@dunmashiku – would you file a separate issue? Happy to help!

**Comment by dunmashiku** [comment]
Thank you! @kevmoo I will create an issue.

**Pull request merged**
